name: Build and Deploy Angular App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Ensures the GITHUB_TOKEN has write permissions

    steps:
    - name: Checkout repository
      uses: actions/checkout@main

    - name: Set up Node.js
      uses: actions/setup-node@main
      with:
        node-version: '24'

    - name: Install dependencies
      run: npm install
      working-directory: ./dadmap

    - name: Build the project
      run: npm run build -- --base-href /dadmap/
      working-directory: ./dadmap

    - name: Deploy to GitHub Pages
      if: success()
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dadmap/dist/dadmap/browser
